__all__ = ["Qwen/Qwen1.5-14B-Chat-GPTQ-Int4", 
           "Qwen/Qwen1.5-32B-Chat-AWQ", 
           "internlm/internlm2-chat-7b", 
           "01-ai/Yi-1.5-9B-Chat",
           "modelscope/Yi-1.5-34B-Chat-AWQ",
           "CohereForAI/aya-23-8B",
           "meta-llama/Meta-Llama-3-8B-Instruct",
           "THUDM/glm-4-9b-chat",
           "Qwen/Qwen2-7B-Instruct",
           "google/gemma-1.1-7b-it",
           "mistralai/Mistral-7B-Instruct-v0.3",
           "microsoft/Phi-3-small-8k-instruct",
           "openbmb/MiniCPM-2B-dpo-bf16",
           "internlm/internlm2_5-7b-chat",
           "google/gemma-2-9b-it"
           ]

model_names = ["Qwen1.5-14B",
               "Qwen1.5-32B",
               "internlm2-7B",
               "Yi-1.5-9B",
               "Yi-1.5-34B",
               "aya-23-8B",
               "Llama-3-8B",
               "ChatGLM4-9B",
               "Qwen2-7B",
               "Gemma-1.1-7B",
               "Mistral-7B-v0.3",
               "Phi3-small",
               "MiniCPM-2B",
               "internlm2.5-7B",
               "Gemma-2-9B"
               ]